# Generated by Django 5.0.6 on 2024-11-07 16:50

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('a_percent', models.FloatField()),
                ('t_percent', models.FloatField()),
                ('c_percent', models.FloatField()),
                ('g_percent', models.FloatField()),
                ('gc_percent', models.FloatField()),
                ('at_gc_ratio', models.FloatField()),
            ],
        ),
    ]
